config/routes.rb
Rails.application.routes.draw do

  resources :contacts

  devise_for :users
    root 'welcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true, length: { minimum: 10, maximum: 10}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # give user their contact
  has_many :contact

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @contacts = Contact.all
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def new
    @contact = Contact.new
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.save
      redirect_to @contact
    else
      render 'new'
    end
  end

  def update
    @contact = Contact.find(params[:id])

    if @contact.update(contact_params)
      redirect_to @contact
    else
      render 'edit'
    end
  end


def destroy
  @contact = Contact.find(params[:id])
  @contact.destroy

  redirect_to contacts_path
end

  private
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :phone_number)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with model: @contact, local: true do |form| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :first_name %><br>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :last_name %><br>
    <%= form.text_area :last_name %>
  </p>

  <p>
    <%= form.label :phone_number %><br>
    <%= form.text_area :phone_number %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contact List</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Phone Number</th>
    <th></th>
  </tr>

  <% @contacts.each do |contact| %>
    <tr>
      <td><%= contact.first_name %></td>
      <td><%= contact.last_name %></td>
      <td><%= contact.phone_number %></td>
      <td><%= link_to 'Show', contact_path(contact) %></td>
      <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
      <td><%= link_to 'Delete', contact_path(contact),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Create another contact', new_contact_path %><br>

app/views/contacts/new.html.erb
<h1>New Contact<h1>

<%= render 'form' %>

<%= link_to 'See contact list', contacts_path %>

app/views/contacts/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @contact.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @contact.last_name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @contact.phone_number %>
</p>

<%= link_to 'Create another contact', new_contact_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Addressbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <p class="navbar-text float-right">
  <% if user_signed_in? %>
    Logged in as <strong><%= current_user.email %></strong>.
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <% else %>
    <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
    <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>
  </p>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h2>Welcome to your Address Book!</h2>
<%= link_to 'Create a new contact', new_contact_path %><br>
<%= link_to 'Contacts List', controller: 'contacts' %>